Лабораторная работа №1
Programming-Classrooms/practicalworks-VladislavYurkov pull request #3
Opened 2023-11-28 19:32 UTC by VladislavYurkov

## Pull Request лабораторной работы №1

### Условие лабраторной работы
Вариант 8

Разработать консольное приложение для вычисления приближённого
значения функции, используя представление ее в виде ряда Тейлора.
Вычисления заканчивать, когда очередное слагаемое окажется по модулю
меньше заданного числа 𝑒𝑝𝑠𝑖𝑙𝑜𝑛, где 0 < 𝑒𝑝𝑠𝑖𝑙𝑜𝑛 < 10−𝑘 , 𝑘 – натуральное
число, 𝑘 > 1. Сравнить полученный результат со значением, вычисленным с
помощью стандартных функций. Значение 𝑥 и 𝑘 ввести по запросу.

8.√(1 + 𝑥) = 1 + (1/2)*𝑥 − (1\(2*4))*x^2 + (1*3/(2*4*6))*𝑥^3 − ⋯ , где 𝑥 ∈ (−1; +1)

2023-11-30 15:33 UTC, Voio77 requested changes
Исправь указанные места 
Работаем, братья и сестра

2023-11-30 15:33 UTC, Voio77 commented on laboratory-task-1/Main.cpp
> +int main()
Добавить отступ 2 строки после подключения модулей

2023-11-30 15:33 UTC, Voio77 commented on laboratory-task-1/Main.cpp
> +	*/
вынести условие лабы за main

2023-11-30 15:33 UTC, Voio77 commented on laboratory-task-1/Main.cpp
> +		if (x >= 1 or x <= -1)
|| вместо or

2023-11-30 15:33 UTC, Voio77 commented on laboratory-task-1/Main.cpp
> +}
добавить логическое разделение и выравнивание для кода

2023-11-30 15:33 UTC, Voio77 commented on laboratory-task-1/Main.cpp
> +	double x, eps, res = 1, el = 1;
измени название переменной el

2023-11-30 15:34 UTC, AlexandrOsiptsov requested changes
Солидарен с Кирюхой

2023-12-10 19:12 UTC, AlexandrOsiptsov requested changes
Просмотри комменты и исправь моменты

2023-12-10 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +using std::cin;
Не делай так

2023-12-10 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +//8. √(1 + 𝑥)
Условие должно быть до текста программы

2023-12-10 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +            throw "Wrong x";
С исключениями работаем через `std::exception`

2023-12-10 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +            throw "Wrong k";
С исключениями работаем через `std::exception`

2023-12-10 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +            throw "Wrong epsilon";
С исключениями работаем через `std::exception`

2023-12-10 19:12 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +        cout << e << '\n';
Ошибки лучше выводить в специальный для этого поток `std::cerr`

2024-01-06 18:22 UTC, AlexandrOsiptsov requested changes

2024-01-06 18:22 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +            taylorSeriesMember *= -x * i / (i+3);
Бинарные операторы мы договорились выделять пробелами

2024-06-17 16:22 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged