Лабораторная работа №3
Programming-Classrooms/practicalworks-VladislavYurkov pull request #8
Opened 2023-12-02 20:08 UTC by VladislavYurkov

## Pull Request лабораторной работы №3

### Условие лабраторной работы
#### Вариант 42
В одномерном массиве, состоящем из п вещественных элементов, вычислить:
- самую длинную цепочку подряд стоящих различных элементов;
- сумму элементов массива, расположенных между первым и последним нулём.
Упорядочить по возрастанию отдельно элементы, стоящие на четных местах, и элементы,
стоящие на нечетных местах.

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +		for (int i = 0; i < lenght; ++i)
почему int?

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +void inputMethod(bool inputMethod, double arr[], int lenght) {
Функция должна делать что-то одно. А здесь всё в кучу. Плюс тип bool, с моей точки зрения, для того, чтобы понять, какой метод ввода массива - неправильный. Там всего два значения. А если я ошиблась, например, нажала 3?

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +		for (int i = 0; i < lenght; ++i)
size_t, не int! Ниже тоже посмотри.

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +	}
Хотелось бы подробнее. Нет двух нулей, есть только один. Плюс снова не тот логический оператор. Мы в иф используем всегда ленивые операторы, а не битовую арифметику.

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +	double arr[LENGTHBASE] = {};
Вообще в задаче просили два варианта сделать, но последний - динамический массив. Не вижу здесь его. Пожалуйста, переделай.

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +
функция принт

2023-12-10 19:17 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +			if (arr[i] > arr[j])
не должно ли это быть функцией?

2023-12-10 19:24 UTC, AnnaSatolina requested changes

2023-12-10 19:24 UTC, AnnaSatolina commented on laboratory-task-3/main.cpp
> +
почему две пустые строки?

2024-01-06 19:43 UTC, AlexandrOsiptsov requested changes
Что значит "не завершена"? Завершай

2024-06-17 16:40 UTC, merged